Fix date fields used inside arithmetic expressions
balena-io-modules/abstract-sql-compiler pull request #151
Opened 2022-11-16 20:06 UTC by fisehara

isNumericValue is evaluated in arithmetic expressions if operands in expression can be used as numericValues.

In SQL statements arithmetic expressions like add/sub are supported for date values.

Perhaps in future this needs to be split into 'canBeArithmeticOperand'

Change-type: minor
Signed-off-by: fisehara <harald@balena.io>

2022-11-16 21:16 UTC, Page- requested changes

2022-11-16 21:16 UTC, Page- commented on src/AbstractSQLRules2SQL.ts
> +		isDurationValue(type)
These are not numeric values and it's actually more accurate to say that you can do `number + number` or `date + number` but not `date + date` but you can do `date - date`, see https://www.postgresql.org/docs/14/functions-datetime.html for a list of the operators for date/time types in postgres

2022-11-16 21:16 UTC, Page- commented on test/abstract-sql/aggregate.ts
> +				sqlEquals(result.query, 'SELECT CURRENT_TIMESTAMP + CURRENT_TIMESTAMP');
This is invalid
```
ERROR:  operator does not exist: timestamp with time zone + timestamp with time zone
LINE 1: SELECT CURRENT_TIMESTAMP + CURRENT_TIMESTAMP

2022-11-18 13:52 UTC, Page- commented on src/AbstractSQLOptimiser.ts
> +		}),
The helper wrapper should be unnecessary?
```suggestion
		(args) => {
			throw new SyntaxError(
				`"AddDate" expects (DateValue, DurationValue | NumericValue) but given ${args}`,
			);
		},
```

2022-11-18 13:54 UTC, Page- commented on src/AbstractSQLRules2SQL.ts
> +			return `DATE_SUB(${a}, ${b})`;
If `a` and `b` are both dates then this would need to be `DATEDIFF`

2022-11-23 16:46 UTC, fisehara commented on src/AbstractSQLRules2SQL.ts
> +	const b = AnyValue(getAbstractSqlQuery(args, 1), indent);
Oh right, thanks!

2022-11-23 16:52 UTC, fisehara commented
@balena-ci I self-certify!

2022-11-23 16:52 UTC, merged